sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t apisani1/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true apisani1/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-48103085463"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
